# Generated by Django 5.0.1 on 2024-01-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_auth', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
                ('date', models.DateField()),
                ('weight', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type_payment', models.CharField(max_length=123)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], default='New', max_length=123)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=20)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from_order', to='main.location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to_order', to='main.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_transport_type', to='driver_auth.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_clicks', to='client_main.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_click', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
