# Generated by Django 5.0.1 on 2024-02-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0001_initial'),
        ('main', '0002_banners_category_news_versionproject_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replydriver',
            name='response',
        ),
        migrations.AddField(
            model_name='order',
            name='volume_m3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from_order', to='main.district'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to_order', to='main.district'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='client_main.order')),
            ],
        ),
    ]
