# Generated by Django 5.0.1 on 2024-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0003_order_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volume_m3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
