# Generated by Django 5.0.1 on 2024-02-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0004_order_volume_m3'),
        ('main', '0007_category_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from_order', to='main.district'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to_order', to='main.district'),
        ),
    ]
