# Generated by Django 5.0.1 on 2024-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0005_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='replydriver',
            name='updated_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
