# Generated by Django 5.0.1 on 2024-03-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0006_replydriver_updated_price'),
        ('main', '0003_alter_country_flag_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from_order', to='main.country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to_order', to='main.country'),
        ),
    ]
