# Generated by Django 5.0.1 on 2024-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_main', '0008_order_file_1_order_file_2_order_file_3_order_file_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True),
        ),
    ]
