# Generated by Django 5.0.1 on 2024-02-01 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_banners_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_seria_number', models.CharField(blank=True, max_length=123, null=True)),
                ('company_name', models.CharField(max_length=223)),
                ('address', models.CharField(blank=True, max_length=333, null=True)),
                ('description', models.CharField(blank=True, max_length=444, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='logistic/logistic')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistic Company',
                'verbose_name_plural': 'Logistic Company',
            },
        ),
    ]
