# Generated by Django 5.0.1 on 2024-02-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_auth', '0001_initial'),
        ('main', '0002_banners_category_news_versionproject_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticcompany',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
