# Generated by Django 5.0.1 on 2024-01-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('color', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('image', models.ImageField(upload_to='transport_types')),
            ],
        ),
        migrations.CreateModel(
            name='TransportWeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('description', models.CharField(max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='DriverAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='driver/avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_company', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDateBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_date_birth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_from', to='main.location')),
                ('direction_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_to', to='main.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_direction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverFullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('last_name', models.CharField(max_length=123)),
                ('surname', models.CharField(max_length=123)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_full_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_seria_num', models.CharField(max_length=23)),
                ('license_expiration_date', models.CharField(max_length=123)),
                ('front_side', models.FileField(upload_to='driver/license/')),
                ('back_side', models.FileField(upload_to='driver/license/')),
                ('face_img', models.FileField(blank=True, null=True, upload_to='driver/license/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria_num', models.CharField(max_length=12)),
                ('front_side', models.FileField(upload_to='driver/passports/')),
                ('with_residence', models.FileField(upload_to='driver/passports/')),
                ('face_img', models.FileField(blank=True, null=True, upload_to='driver/passports/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payment_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('description', models.CharField(max_length=233)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_types', to='driver_auth.manufacturertype')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=123)),
                ('front_side_img', models.ImageField(upload_to='technical_passport/')),
                ('back_side_img', models.ImageField(upload_to='technical_passport/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_technical_passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_front', models.FileField(upload_to='transport_images/')),
                ('transport_left', models.FileField(upload_to='transport_images/')),
                ('transport_behind', models.FileField(upload_to='transport_images/')),
                ('transport_right', models.FileField(upload_to='transport_images')),
                ('row_seats', models.FileField(upload_to='transport_images/')),
                ('baggage', models.FileField(upload_to='transport_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_transport_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_made_date', models.CharField(max_length=45)),
                ('tons_from', models.PositiveIntegerField()),
                ('tons_to', models.PositiveIntegerField()),
                ('color_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_auth.colortransport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_transport_details', to=settings.AUTH_USER_MODEL)),
                ('model_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_auth.modeltransport')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_auth.transporttype')),
            ],
        ),
        migrations.AddField(
            model_name='transporttype',
            name='transport_wight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_weight_types', to='driver_auth.transportweighttype'),
        ),
    ]
