# Generated by Django 5.0.1 on 2024-01-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertransportdetails',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='drivertransportdetails',
            name='transport_weight_type',
        ),
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_from', to='main.location'),
        ),
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_to', to='main.location'),
        ),
    ]
