# Generated by Django 5.0.1 on 2024-02-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0001_initial'),
        ('main', '0002_banners_category_news_versionproject_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_from', to='main.location'),
        ),
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_to', to='main.location'),
        ),
        migrations.AlterField(
            model_name='technicalpassport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
