# Generated by Django 5.0.1 on 2024-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0002_alter_driverdirection_direction_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransportdetails',
            name='volume3_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertransportdetails',
            name='volume3_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
