# Generated by Django 5.0.1 on 2024-03-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0003_drivertransportdetails_volume3_from_and_more'),
        ('main', '0003_alter_country_flag_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_from', to='main.country'),
        ),
        migrations.AlterField(
            model_name='driverdirection',
            name='direction_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_to', to='main.country'),
        ),
    ]
