# Generated by Django 5.0.1 on 2024-02-12 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientavatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_avatar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientfullname',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_full_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
