# Generated by Django 5.0.1 on 2024-03-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0002_alter_clientavatar_user_alter_clientfullname_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdatebirth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_birth', to=settings.AUTH_USER_MODEL),
        ),
    ]
