# Generated by Django 5.0.1 on 2024-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners_category_news_versionproject_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
