# Generated by Django 5.0.1 on 2024-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_chat_created_at_remove_chat_user1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('version_text', models.CharField(max_length=333)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Optional', 'Optional'), ('Forced', 'Forced'), ('Shutdown', 'Shutdown')], max_length=123)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
