# Generated by Django 5.0.1 on 2024-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[(1, 'Driver'), (2, 'Client'), (3, 'Company'), (4, 'Administrator')], default='Client', max_length=20),
        ),
    ]
