# Generated by Django 5.0.1 on 2024-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Client', 'Client'), ('Company', 'Company'), ('Administrator', 'Administrator')], default='Client', max_length=20),
        ),
    ]
